config/routes.rb
Rails.application.routes.draw do
  
  resources :wikitwitters
  root "wikitwitters#index"
  

end

app/models/wikitwitter.rb
class Wikitwitter 
    # < ActiveRecord::Base
   include ActiveModel::Model
    

  attr_accessor :tweet

  def client
    @client ||= Twitter::REST::Client.new do |config|
        config.consumer_key        = "SAlIdSPTGYb1DH7DCocckJ5dm"
        config.consumer_secret     = "llEG7QHrLowfFy4O7YEWvYGFtgVD4WrcKoRpxonUCmQ7BfR3y9"
        config.access_token        = "2356601096-18JEtGHVlyPbODgSOwfUOcd28bKgEye0o6EkqIf"
        config.access_token_secret = "RPqhltFZDZX5XDfs2k6kJ3UPCXcnCB4QwoAS1OIo74xLk"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wikitwitters_controller.rb
class WikitwittersController < ApplicationController
    require "wikipedia"
    require "twitter"


    def index
        # get page title
        @page = Wikipedia.find_random()
        title = @page.title
        
        # create an instance
        @twitter ||= Wikitwitter.new
        
        if @twitter
            @result = @twitter.client.search(title, exclude: "retweets", count: 15)

        end
    end
    
    def new
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wikitwitters_helper.rb
module WikitwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "jquery.mobile-1.4.5.min", :media => "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page" class = 'wrapper'>

<%= yield %>

</div>
</body>
</html>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://code.jquery.com/color/jquery.color-2.1.2.min.js"   integrity="sha256-H28SdxWrZ387Ldn0qogCzFiUDDxfPiNIyJX7BECQkDE="   crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<!--<script src="//ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js"></script>-->
<%= javascript_include_tag 'jquery.mobile-1.4.5.min', 'data-turbolinks-track' => true %>

app/views/wikitwitters/index.html.erb
<!--Title-->
<div class="header" data-role="header">
	<h1 class = 'Wikititle'><a href = <%= "https://en.wikipedia.org/wiki/" + @page.title %> style="color: #666;, width:100%;"><%= @page.title %></a></h1>
</div>
<!--go to the list of favorite-->
<div class="header">
	<div class = "favorite"><%= link_to "wanna see your favorites ?", new_wikitwitter_path, :style=>"color:#666;" %></div>
</div>

<!--from wikitwitters-->
<main role="main">
<% @result.each do |tweet| %>
	<!--this if doesn't work-->
	<% if tweet == "" || tweet.nil? then%>
		<p>hoge</p>
		<% break %>
	<% else %>
	<div class = 'tweet_area'>
		<div class='forcookieicon'><%= tweet.user.profile_image_url %></div>
		<div class = 'twitter_icon'><img src = '<%= tweet.user.profile_image_url %>' alt = 'icon'></img></div>
		<div claas = 'twitter_user'><span claas = 'twitter_username'><%= tweet.user.name %></span></div>
		<div class = "fav"></div>
		<div class = 'twitter_contents'><%= tweet.text %></div>
		<% if tweet.media? then %>
			<% tweet.media.each do |value| %>
	       		<img src =	<%=value.media_uri %> class = 'twitter_pic'>
	       		<div class = "forcookiemedia"><%=value.media_uri %></div>
    		<% end %>
    	<% end %>
    </div>
    <% end %>
<% end %>
</main>

app/views/wikitwitters/new.html.erb
<div class="header" data-role="header">
    <h1>Your favotites</h1>
</div>
<div class="header">
	<div class = "favorite"><%= link_to "Back to timeline", root_path, :style=>"color:#666;" %></div>
</div>

<% temp = cookies["fav"].split(',') unless cookies["fav"].nil? %>
<% if temp.nil? || temp == [] then%>
<p class = "nofav">No favorite<p>

<% else %>
<% j = 0%>
<% limit = temp.length / 4 %>
<% tweets = [] %>
<% for i in 0..(limit) do
    tweets.push([temp[j],temp[j+1],temp[j+2],temp[j+3]])
    j += 4 %>
<% end %>
<% tweets.each do |tweet| %>
	<% if tweet[1].nil? || tweet[1] == "" then %>
	<% else %>
	<div class = 'tweet_area' style = "background-color: rgba(255,255,153,0.6);">
		<div class='forcookieicon'><%= tweet[0] %></div>
		<div class = 'twitter_icon'><img src = '<%= tweet[0] %>' alt = 'icon'></img></div>
		<div claas = 'twitter_user'><span claas = 'twitter_user'><%= tweet[1] %></span></div>
		<div class = "fav">favorite</div>
		<div class = 'twitter_contents'><%= tweet[2] %></div>
		<% if tweet[3].nil? || tweet[3] == "" then %>
		<% else %>
       		<img src =	<%= tweet[3] %> class = 'twitter_pic'>
       		<div class = "forcookiemedia"><%= tweet[3] %></div>
		<% end %>
    </div>
    <% end %>
    
<% end %>
<% end %>